name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    description: 'token'
    required: true
  pattern:
    description: 'pattern to detect the place to locate the table'
    required: false
    default: '<!-- issueTable -->'
runs:
  using: 'node12'
  main: 'dist/index.js'
